### ISSUE TITLE
Credential manager `osxkeychain` not being built

### ISSUE THREAD

**Issue by mfansler** [AnacondaRecipes/git-feedstock#5]
[A recent StackOverflow question](https://stackoverflow.com/q/58403189/570918) pointed out trying to use the `osxkeychain` credential manager via

    git config --global credential.helper osxkeychain

fails when pushing. Apparently the build step for this component [has been incorporated into Conda Forge](https://github.com/conda-forge/git-feedstock/commit/19a009acf996bec448b1a97994252e5184b7cb22), but this fork has yet to merge it.

**Comment by jjhelmus** [comment]
Thanks for opening an issue on this topic.  I added this feature to this fork in e1d9304ea2c642385f793f782b7f5f647f02ab08.  The git 2.23.0 packages in `defaults` include support for `osxkeychain`.
